version: "3.9"

services:
  api:
    build: ./api
    container_name: telemetria_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: telemetria_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_telemetrias
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: telemetria_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
