[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
# todos los tests marcados como async def se ejecutan automáticamente en un event loop de asyncio
# gracias a este archivo.  No es necesario añadir decoradores manuales en cada test.