"""crear tablas iniciales

Revision ID: 747c88254e2a
Revises: 
Create Date: 2026-02-05 18:07:47.340999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747c88254e2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planta_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('TEMPERATURA', 'PRESION', 'HUMEDAD', 'VIBRACION', 'CAUDAL', name='tiposensordb'), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensores_planta_id', 'sensores', ['planta_id'], unique=False)
    op.create_table('telemetrias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetrias_payload_hash'), 'telemetrias', ['payload_hash'], unique=False)
    op.create_index('ix_telemetrias_sensor_timestamp', 'telemetrias', ['sensor_id', 'timestamp'], unique=False)
    op.create_index('ix_telemetrias_timestamp', 'telemetrias', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetrias_timestamp', table_name='telemetrias')
    op.drop_index('ix_telemetrias_sensor_timestamp', table_name='telemetrias')
    op.drop_index(op.f('ix_telemetrias_payload_hash'), table_name='telemetrias')
    op.drop_table('telemetrias')
    op.drop_index('ix_sensores_planta_id', table_name='sensores')
    op.drop_table('sensores')
    op.drop_table('plantas')
    # ### end Alembic commands ###
